### ISSUE TITLE
Inscrutable error when 'Member e r' is required but not given

### ISSUE THREAD

**Issue by bolt12** [polysemy-research/polysemy#227] opened 2019-09-10 10:15 UTC
Hi,

I'm trying to do the following:

```Haskell
discover :: Members '[Socket, Multicast] r => Sem r (Maybe NS.Socket)
discover = do
    ip <- multicast "239.255.255.250" 1982
    connect ip

program :: Members '[Config, Socket, Resource] r => Sem r ()
program = do 
    commands <- listToMaybe <$> getArguments
    case commands of
        Nothing -> return ()
        Just cmd -> do
            (host, port) <- getAddress
            ip <- (resolve host port)
            case ip of
                Nothing -> discover >>= maybe (return ()) (unicast cmd)
                _ -> connect ip >>= maybe (return ()) (unicast cmd)
```

As you can see, my `program` uses `discover` function. I am getting an error like this:

```Haskell
    • Could not deduce: Polysemy.Internal.Union.IndexOf
                          r (Polysemy.Internal.Union.Found r Multicast)
                        ~ Multicast
        arising from a use of ‘discover’
      from the context: Members '[Config, Socket, Resource] r
        bound by the type signature for:
                   program :: forall (r :: [(* -> *) -> * -> *]).
                              Members '[Config, Socket, Resource] r =>
                              Sem r ()
        at app/Main.hs:24:1-60
    • In the first argument of ‘(>>=)’, namely ‘discover’
      In the expression: discover >>= maybe (return ()) (unicast cmd)
      In a case alternative:
          Nothing -> discover >>= maybe (return ()) (unicast cmd)
    • Relevant bindings include
        program :: Sem r () (bound at app/Main.hs:25:1)
   |
33 |                 Nothing -> discover >>= maybe (return ()) (unicast cmd)
   |                            ^^^^^^^^
```

Is there anyway that I can do this without copy pasting the `discover` definition into `program`?

**Comment by KingoftheHomeless** [comment] 2019-09-10 10:25
Isn't this simply because `program` lacks the `Member Multicast r` constraint? 

Even if that's the case, the error is really damn weird. `Polysemy` attaches custom error messages to "ambiguous-use" errors, but this gives an unsatisfied equality constraint error. Perhaps that's caused by the plugin?

**Comment by KingoftheHomeless** [comment] 2019-09-10 10:31
You have error messages enabled, right?

**Comment by KingoftheHomeless** [comment] 2019-09-10 10:39
Wait, isn't this because `Member` uses `MemberNoError`?:
```haskell
type Member e r = MemberNoError e r
```
Shouldn't this be `MemberWithError`? `MemberNoError` doesn't generate "ambiguous send" when `IndexOf r (Found r e)` gets stuck. @isovector

**Comment by bolt12** [comment] 2019-09-10 10:56
@KingoftheHomeless Thanks for your help! Indeed it was because I forgot the `Multicast` constraint!

But as you asked I haven't disabled nothing and I do agree that the error message is a bit misleading.

**Comment by KingoftheHomeless** [comment] 2019-09-10 11:08
Ok, I'll rename the issue to reflect this.

**Comment by isovector** [comment] 2019-09-10 11:22
Yeah, the error here sucks. We used to emit a custom error in this case, but it got more in the way when other things went wrong. It would be nice to have a fix for this, but I don't think it's feasible given today's level of technology.

**Comment by KingoftheHomeless** [comment] 2019-09-10 12:26
If I understand #143, the problem with `Member = MemberWithError` is when interpreters are run with incorrect arguments, like the following:

```haskell
run $ runState (put (5 :: Int) :: forall r. Member (State Int) r => Sem r ())
```

With `MemberNoError`, this spits out a reasonable error message that even says "perhaps you have applied `runState` to too few arguments", but with `MemberWithError`, it spits out this garbage:
```haskell
    * Ambiguous use of effect 'State'
      Possible fix:
        add (Member (State Int) r1) to the context of
          the type signature
```
Which can be straight-up harmful.

That is pretty damn bad, yeah, but the error message in the OP isn't acceptable either; it leaves the user with no understanding what could've gone wrong UNLESS they understand that the failed unification means a `Member` constraint is missing.
A band-aid solution would be adding something like following to the documentation for `Member`:

```haskell
-- If you're encountering an error message like the following when writing polymorphic code:
--
-- @
--  * Couldn't match type `Polysemy.Internal.Union.IndexOf
                         r (Polysemy.Internal.Union.Found r e)'
                 with `e'
-- @
--
-- or
--
-- @
-- * Could not deduce: Polysemy.Internal.Union.IndexOf
--                       r (Polysemy.Internal.Union.Found r e)
--                     ~ e
--@
--
-- That means a @Member e r@ constraint is required by some method you're using, but not
-- provided by the constraints placed upon @r@. Unfortunately, due to limitations of type families,
-- we can't improve this error message without worsening others.
```

We should also rewrite all derived actions in `Polysemy` like `modify` to use `MemberWithError` instead of `Member`.

**Comment by isovector** [comment] 2019-09-10 12:42
It's more egregious than that; you'll also get the `Ambiguous effect` error if you forget an argument to an action, or give a type hole. GHC's type errors are just too eager to do anything good here afaik.

**Comment by KingoftheHomeless** [comment] 2019-09-10 12:51
Damn, you're right. So is there no way to not break on a custom type error? The bad error messages would be fine if the others also got through. Perhaps a GHC issue should be opened for that.

**Comment by isovector** [comment] 2019-09-10 12:54
That's a good idea --- a `TypeError` that only gets emitted if there are no other type errors GHC wants to emit first.

**Comment by isovector** [comment] 2019-09-10 12:58
https://gitlab.haskell.org/ghc/ghc/issues/16906#note_221198

**Comment by KingoftheHomeless** [comment] 2019-09-10 13:24
Do you mean a `TypeError` that emits an error that's part of `report2` instead of `report1` [here?](https://gitlab.haskell.org/ghc/ghc/blob/master/compiler/typecheck/TcErrors.hs#L582) That'd make sense.

**Comment by bolt12** [comment] 2019-09-11 13:16
If I heard right, there isn't a good solution for this problem (?) Is there anything I can try to figure/read so I can be more familiar with this issue and try comming up with something?

Also is there anyway to help inference with high order functions? For example when I use something like this inside some `Sem` function program (which has the proper constraints)

```Haskell
maybe (f >> h) g
```

the compiler says that I need to add the signature for `f >> h`. I'm sorry I don't have a proper example to replicate but are you familiar with this issue?

**Comment by KingoftheHomeless** [comment] 2019-09-11 14:40
Unfortunately, I suspect any solution to this would require a ton of work, investment, and knowledge. It's a very big problem to tackle.
If you want to contribute and do something about this, I'd recommend implementing the band-aid I suggested above; adding documentation to `Member` explaining the unclear errors.

The main issue boils down to that in order to get custom type errors, we use [GHC's API for such](https://gitlab.haskell.org/ghc/ghc/wikis/proposal/custom-type-errors) (which can be accessed via [`GHC.TypeLits`](https://hackage.haskell.org/package/base-4.12.0.0/docs/GHC-TypeLits.html#t:TypeError). In order to fire these off only when something has gone wrong, we use a [trick](https://kcsongor.github.io/report-stuck-families/) to detect when the underlying machinery of `Member` breaks. The problem is that custom type errors _cause GHC to not emit any other type errors after them_, even though, in the case of our custom type errors, _we really want it to_: The custom type errors alone may be worthless or even harmful when the underlying root issue is something else that GHC can explain better. In fact, we don't even want to display our custom type errors if there's something even more fundamentally wrong; like providing a `Sem r ()` when something is expecting a function `String -> String` .

In order to have custom type errors, but also defer to GHC's default type errors when something more significant breaks, we need one of the following:

1. A way to detect if something fundamentally wrong has happened, and if so, not emit custom type errors. The trick we're using is not powerful enough to do this, and I doubt it's unlikely that it will ever be possible.
2. A variant of `TypeError` which emits an error that doesn't suppress other type errors, but can get suppressed by other, more serious, type errors. This requires support from GHC.

Since we don't have either for the moment, we chose to not have `Member` report missing constraints; instead, only `MemberWithError` does, which is what actions generated using `makeSem` uses. These are more likely to be used in a context where the custom type errors won't obfuscate something more important (but not guaranteed; `censor @String (tell "no")` still reports the wrong thing).

Personally, I think the way to solve this is contributing to GHC and implementing solution 2. above. However, adding 2. to GHC could require its own GHC proposal.

See also [this discussion](https://gitlab.haskell.org/ghc/ghc/issues/16906) for more comprehensive info about the shortcomings of GHC's custom type errors.

**Comment by KingoftheHomeless** [comment] 2019-09-11 14:43
Regarding the other question: I'm sorry, but I don't know of any inference issues that are specific to higher-order functions, and I don't understand your example. Doing something like this works fine:

```haskell
ex :: Members '[Trace, Error String] r => Sem r ()
ex = do
  m <- pure (Just ())
  maybe (trace "trace" >> throw "error") (\_ -> pure ()) m
```

For inference problems in general, have you tried using [polysemy-plugin](https://hackage.haskell.org/package/polysemy-plugin)? It eliminates almost all ambiguity issues you'd run into, and I recommend that you always use it whenever you can.

If `polysemy-plugin` still doesn't work to eliminate these issues, then I'm going to need concrete code for me to examine; if you run into that problem again, create a separate issue for it with the relevant piece of code.

**Comment by bolt12** [comment] 2019-09-11 15:21
@KingoftheHomeless  Thanks for the thorough explanation! Unfortunately that's out of my comfort zone... I wish it wasn't! I'll try and make myself more familiar with it

Regarding the issue I think the plugin was what I was looking for! Thanks!

**Closed** 2021-11-16 23:01 UTC
Labels: custom errors
