### ISSUE TITLE
Plugin panics tracking issue

### ISSUE THREAD

**Issue by sorki** [polysemy-research/polysemy#356] opened 2020-06-26 15:05 UTC
GHC 8.10.1 related

- https://github.com/polysemy-research/polysemy-zoo/issues/65
- #354 
- #355

For most of my lib I've switched to enabling plugin for only few modules via `pragma` instead of enabling it globally. 

What's interesting is that this only manifests on full builds via `cabal build` but not in `cabal repl`.

**Comment by adamConnerSax** [comment] 2020-09-28 13:42
On 8.10.2 it manifests for me (sometimes, anyway) in ```cabal new-repl``` as well.

**Comment by googleson78** [comment] 2020-09-28 15:03
Anyone with some comparatively minimal reproducer? I'm not using 8.10 and so haven't gotten any panics :/ (at least not ones that weren't caused by non-compiling code)

**Comment by TheMatten** [comment] 2020-10-23 09:03
@sorki you can try https://github.com/polysemy-research/polysemy/pull/382

**Comment by tek** [comment] 2020-10-23 15:06
can confirm that the panic in #354 doesn't occur anymore.

**Comment by isovector** [comment] 2021-11-16 21:37
Closing this. Feel free to reopen if you think it's still an issue.

**Closed by isovector** 2021-11-16 21:37 UTC
