### ISSUE TITLE
Better error message for ambiguous effect when r ~ '[]

### ISSUE THREAD

**Issue by isovector** [polysemy-research/polysemy#89] opened 2019-06-08 02:20 UTC
#88 points out a case in which `Lift IO` isn't in the effect stack, but the user was trying to `runM` it out anyway. In this case, `polysemy` is looking for a `Find (Lift IO) '[]` constraint, which is obviously not your run-of-the-mill ambiguous error effect.

Instead we should custom match on `'[]` and provide a better message.

**Comment by isovector** [comment] 2019-06-08 04:22
See https://github.com/isovector/polysemy/blob/c57f79bce45939dd173af4bde73cf3849bbe5f34/src/Polysemy/Internal/CustomErrors.hs#L86 --- we'd just need to add a case for `AmbiguousSend '[] e`.

**Comment by cah6** [comment] 2019-06-10 14:15
I'd like to try out this one! I'll start looking at it later tonight, if nobody else has started.

**Comment by isovector** [comment] 2019-06-15 23:21
I've added a test for this in #113

**Comment by cah6** [comment] 2019-06-16 19:11
@isovector nice, I started looking at this today (ended up not having the time I thought this week) and immediately thought it would be nice if there was some way to automatically test these sort of "user" errors fixes. I'll make sure to rebase onto your latest change.

**Comment by cah6** [comment] 2019-06-16 20:28
@isovector running into a bit of trouble here, maybe you can help.

The issue is that if I add `AmbiguousSend '[] e = ...` to the end of the `AmbiguousSend` family, it complains of overlapping instances:
```
src/Polysemy/Internal/CustomErrors.hs:102:3: warning:
    Type family instance equation is overlapped:
      forall t k1 k2 (e :: t).
        AmbiguousSend '[] e = (TypeError ...)
          -- Defined at src/Polysemy/Internal/CustomErrors.hs:102:3
    |
102 |   AmbiguousSend '[] e =
```
and never actually gets to it (error messages never change to what I provide). So I tried moving it to the beginning of the family. In that case it does output this for the `runningTooManyEffects'WRONG` test, but it also breaks 3 other existing tests, i.e:
```
test/DoctestSpec.hs:20: failure in expression `:{
 foo :: Sem r ()
 foo = put ()
:}'
expected: ...
          ... Ambiguous use of effect 'State'
          ...
          ... (Member (State ()) r) ...
          ...
 but got: 
          <interactive>:53:8: error:
              • Couldn't match type ‘Polysemy.Internal.Union.IndexOf
                                       r (Polysemy.Internal.Union.Found r (State ()))’
                               with ‘State ()’
                  arising from a use of ‘put’
              • In the expression: put ()
                In an equation for ‘foo’: foo = put ()
              • Relevant bindings include
                  foo :: Sem r () (bound at <interactive>:53:2)
```

Regarding the actual error message, the existing message output does mention the lack of (Lift IO) in the effect members, though I'm assuming the part you don't like is that it's a bit obfuscated. So just to run it by you, when I get it working I was going to aim to make it look something like:
```
Tried to handle effect 'Lift IO' but it was never provided
Possible fix:
  add (Member (Lift IO)) to the context of the type signature
```

**Comment by TheMatten** [comment] 2019-06-16 20:43
Other equations are defined like `AmbiguousSend r ..` where `r` can be anything and `e` matches all possible cases - that means that your equation never gets to be evaluated when on bottom. As for the error, because we are now pattern matching on list, and in case above that list is unknown, `AmbiguousSend` probably gets "stuck" (doesn't evaluate), because it doesn't know what it should evaluate to... It seems like this one will be a little bit more complicated... :slightly_smiling_face:

**Comment by isovector** [comment] 2019-06-16 20:43
@cah6 try putting the type instance before the `AmbiguousSend r (e a b c d f)` case. Closed type families work the same as value-level pattern matching; they're tried in order.

**Comment by isovector** [comment] 2019-06-16 20:44
Sorry, misread. Not sure why it's breaking. Can you upload the code somewhere?

**Comment by cah6** [comment] 2019-06-16 21:11
Would push to a PR but looks like I don't have permission. Anyhow it's just a short change to 1 file right now:
```
diff --git a/src/Polysemy/Internal/CustomErrors.hs b/src/Polysemy/Internal/CustomErrors.hs
index ea0d368..df66526 100644
--- a/src/Polysemy/Internal/CustomErrors.hs
+++ b/src/Polysemy/Internal/CustomErrors.hs
@@ -68,6 +68,12 @@ type family PrettyPrint (vs :: [k]) where


 type family AmbiguousSend r e where
+  AmbiguousSend '[] e =
+    TypeError
+        -- temp message, will add more to it later
+        ( 'Text "Expected: " ':<>: 'ShowType e ':<>: 'Text " but it was not in the effect list."
+        )
+
   AmbiguousSend r (e a b c d f) =
     TypeError (AmbigousEffectMessage r e (e a b c d f) '[a, b c d f])
```

**Comment by isovector** [comment] 2019-06-16 21:13
Okay, hold off until #115 lands, when you can use the new `IsStuck` machinery first to determine if `r` is stuck before pattern matching on it.

**Comment by isovector** [comment] 2019-06-16 21:14
Landed. That was fast ;)

**Comment by isovector** [comment] 2019-06-16 21:20
@cah6 consider forking a copy of `polysemy` and doing your work there; then you can open PRs against the main branch: https://help.github.com/en/articles/fork-a-repo

**Comment by cah6** [comment] 2019-06-16 23:32
Gah I'm dumb, was thinking of a different workflow. Thanks. 😄 

I think I could use some `IfStuck` machinery myself here 😛. My initial thought was that I could take my previous example but give `'[]` the name `r` and check `IfStuck` on this `r`, kind of like:
```
AmbiguousSend r@('[]) e = IfStuck r (TypeError ('Text "Some stuck message?")) (...my new message...)
```
but that doesn't work since it looks like you can't do this `varName@pattern` pattern matching syntax on type families. 

So then I tried to instead make some helper family that could pattern match once I ran `IfStuck` on `r`, like:
```
type family SendHelper r e where
  SendHelper '[] e =
              TypeError ('Text "Expected: " ':<>: 'ShowType e ':<>: 'Text " but it was not in the effect list.")
  SendHelper r e = 
              TypeError
            ( 'Text "Could not deduce: (Member "
        ':<>: 'ShowType e
        ':<>: 'Text " "
        ':<>: 'ShowType r
        ':<>: 'Text ") "
        ':$$: 'Text "Fix:"
        ':$$: 'Text "  add (Member "
        ':<>: 'ShowType e
        ':<>: 'Text " "
        ':<>: 'ShowType r
        ':<>: 'Text ") to the context of"
        ':$$: 'Text "    the type signature"
            )
```
and calling that instead:
```
AmbiguousSend r e = IfStuck r (TypeError ('Text "Some stuck message?")) (SendHelper r e)
```
but I get the same `Union.IndexOf` as above and am not sure how else to handle it...

**Comment by isovector** [comment] 2019-06-17 00:50
I was thinking something like this:

```haskell
type BetterAmbiguousSend r e = IfStuck r (AmbiguousSend r e) (NewSendFcf r e)

data NewSendFcf :: [(* -> *) -> * -> *] -> ((* -> *) -> * -> *) -> Expr Constraint
type instance Eval (NewSendFcf r e) = NewAndImprovedAmbiguousSendThatWon'tGetStuckOnEmptyList r e
```

**Comment by isovector** [comment] 2019-06-18 14:07
@cah6 any luck on this front?

**Comment by cah6** [comment] 2019-06-18 14:24
@isovector I tried out what you last mentioned, but maybe part of it wasn't right because I could never get it to output my message when `r ~ '[]` but not revert to `...Union.IndexOf...` messages for other cases. You might want to take a look yourself, sorry!!

In good news, your recent addition of the doctest tests was very helpful here! Awesome, concise way of making sure that certain compiler errors are changed while others aren't.

**Closed** 2019-06-30 03:37 UTC
Labels: custom errors, enhancement, good first issue
