### ISSUE TITLE
Interop with ResourceT

### ISSUE THREAD

**Issue by AlexeyRaga** [polysemy-research/polysemy#109] opened 2019-06-15 07:28 UTC
I have a bunch of APIs that are somehow heavy on using `ResourceT`. `Amazonka` could be a good example.

In MTL style I would use it like:

```
handleFile s3uri =
    runResourceT $ do
        content <- downloadLazyBS s3uri
        doSomethingUseful content
```

The idea here is to "detonate" `ResourceT` as soon as I am done with it.

How do I use `downloadLazyBS` with `polysemy`? 
Should something like `absorb` work with `ResourceT`?

**Comment by AlexeyRaga** [comment] 2019-06-15 13:33
I came up with this so far, but it feels crazy:

```
bracketResource :: (Member (Lift IO) r, Member Resource r) => ResourceT IO a -> (a -> Sem r b) -> Sem r b
bracketResource ma f =
  bracket (sendM $ alloc ma) (\(_, clean) -> sendM clean) (\(a, _) -> f a)
  where
    alloc f = runResourceT $ do
      res <- f
      actions <- getAllKeys >>= traverse unprotect
      let cleanup = sequence_ (catMaybes actions)
      pure (res, cleanup)

--------------------------------------------------------------------------------------

getAllKeys :: ResourceT IO [ReleaseKey]
getAllKeys = do
  iom <- getInternalState
  m <- getMap iom
  pure $ ReleaseKey iom <$> IntMap.keys m

getMap :: MonadIO m => IORef ReleaseMap -> m (IntMap.IntMap (ReleaseType -> IO ()))
getMap iom = liftIO $
  readIORef iom >>= \case
    ReleaseMap _ _ m -> pure m
    ReleaseMapClosed -> pure IntMap.empty
```

**Comment by isovector** [comment] 2019-06-15 16:13
The zoo has some [fancy stuff for doing interop with MTL](https://hackage.haskell.org/package/polysemy-zoo-0.2.0.0/docs/Polysemy-MTL.html#t:CanonicalEffect). However, an easier approach is to probably instead just run your entire `polysemy` stack over `Lift (ResourceT IO)` instead of over `Lift IO`. [`runIO` will be helpful](https://hackage.haskell.org/package/polysemy-0.4.0.0/docs/Polysemy-IO.html#v:runIO).

To sketch it out:

```haskell
main :: IO ()
main = runResourceT . runM . runIO @(ResourceT IO) $ do
  sendM $ putStrLn "hello" -- ok to use IO
  sendM $ something with ResourceT -- ok to use ResourceT also!
```

**Comment by AlexeyRaga** [comment] 2019-06-16 08:24
Thanks!
I actually tried to use it in an interpreter, but couldn't make it compile...

**Comment by AlexeyRaga** [comment] 2019-06-16 10:13
Is it even possible to use such bracketing in an interpreter?
What I want is to close the resource explicitly and not have it hanging in a global `ResourceT`. 
So I either need a scoped `runResourceT`, or a bracket that is similar than mine above.

But when I do this:

```haskell
runStoreS3 e = interpret $ \case
  Download u            -> bracketResource (runAws e (downloadFromS3Uri u)) (sendM @IO . pure)
```

I see that cleanup action is called earlier than I expect, perhaps immediately after `sendM` sends the value, but before my code is done with it...

Do I need a higher order effect to model it?

**Comment by isovector** [comment] 2019-07-04 02:34
Sorry, this fell off my radar. Are you still having issues?

**Comment by AlexeyRaga** [comment] 2019-07-04 03:31
Yes, I couldn't figure out how to use `runResourceT` inside the interpreter in a way that would bracket each action.
I thought that my `bracketResource` would do the trick, but somehow I see that closing is happening way earlier that I expected...

**Comment by isovector** [comment] 2019-07-04 05:12
Did you try the approach in https://github.com/polysemy-research/polysemy/issues/109#issuecomment-502379196?

**Comment by AlexeyRaga** [comment] 2019-07-04 12:10
I don't think that running `ResourceT` "globally" would work in my situation.
In my case I have to close resources as soon as I am done with them and without waiting until the whole `ResourceT` is detonated.
One example would be streaming files from S3 where `Amazonka` gives us a `ByteString` within `ResourceT`.  But if I don't consume that `ByteString` till the end then the resource won't be closed until the final `runResourceT` happens.

**Comment by isovector** [comment] 2019-07-04 12:17
I am reasonably sure it will. `ResourceT` supports closing resources within the `ResourceT` monad; you don't need to wait until `runResourceT` for that to happen --- eg https://www.stackage.org/haddock/lts-13.27/resourcet-1.2.2/Control-Monad-Trans-Resource.html#v:release.

But if for some reason that doesn't work for you, you can always just `runResourcet` each `ResourceT` action:

```haskell
runLiftedResourceT :: Member (Lift IO) r => Sem (Lift (ResourceT IO) ': r) a -> Sem r a
runLiftedResourceT = interpret $ \case
  Lift m -> sendM @IO $ runResourceT m
```

**Comment by AlexeyRaga** [comment] 2019-07-04 13:03
Yes, there is `release` which is handy if you have `ReleaseKey`. 
Most of the time you don't because library functions would just give you `MonadResource m => ... m a`. `Amazonka` is certainly like that: resources allocation happens somewhere within the library and consumers only get `ResourceT`.

What I tried to express is something like:

```haskell
data Store m a where
  Download  :: S3Uri -> Store m (Maybe ByteString)
  Upload    :: S3Uri -> ByteString -> Store m ()
```

and then have an interpreter that would do `runResourceT` for `Download`.

I will try playing with your `runLiftedResourceT` example, thanks! 
In its current state it would probably mean that _all_ `ResourceT` actions will now be scoped, as it is not up to a particular interpreter anymore, but perhaps it can be worked around?

My specific case is exactly like that: I read many streams from S3, read parts of them and close them, but I also have some streams that I write these parts too, and those must survive longer...

**Comment by isovector** [comment] 2019-07-04 13:07
You can also do the `sendM . runResourceT` trick in an interpreter of `Store` if you only want to scope those actions.

**Comment by AlexeyRaga** [comment] 2019-07-04 23:10
Thanks, I'll try these!

**Comment by AlexeyRaga** [comment] 2019-07-07 10:41
I feel stupid, but I still can't get it right :(

Here is what I have:

```haskell
runStoreS3' :: (HasEnv env
  , Member (Lift IO) r
  , Member (Lift (ResourceT IO)) r
  )
  => env
  -> Sem (Store ': r) a
  -> Sem r a

runStoreS3' e = 
  interpret $ \case
    Download u -> getBS e u
  where
    getBS :: (HasEnv env, Member (Lift (ResourceT IO)) r) => env -> S3Uri -> Sem r (Maybe ByteString)
    getBS env uri = sendM @(ResourceT IO) (runAws @(ResourceT IO) env (downloadFromS3Uri uri))
```

This compiles, but it doesn't scope the resource that is coming from `getBS`.

How do I change `runStoreS3'` to use `runResourceT` in it?

**Comment by AlexeyRaga** [comment] 2019-07-09 03:57
I have tried your `runLiftedResourceT` example, and to my surprise it didn't work either,  the resource gets closed before I have a chance of using it.

Here is the code:

```haskell 
runStoreS3' :: (HasEnv env, Member (Lift (ResourceT IO)) r)
  => env
  -> Sem (Store ': r) a
  -> Sem r a
runStoreS3' env =  interpret $ \case
  Download uri -> sendM @(ResourceT IO) $ do
    bs <- runAws @(ResourceT IO) env (downloadFromS3Uri uri)
    -- liftIO $ print (LBS.length <$> bs)
    pure bs

runLiftedResourceT :: Member (Lift IO) r => Sem (Lift (ResourceT IO) ': r) a -> Sem r a
runLiftedResourceT = interpret $ \case
  Lift m -> sendM @IO $ runResourceT m

runMain :: IO ()
runMain = do
  env <- mkEnv Oregon (\_ _ -> pure ())
  runM
    . runLogConsole
    . runLiftedResourceT
    . runStoreS3' env
    $ stuff
```

And here is what I get as a result:
```
[Info] Let's start
[Info] Got: Just 0
[Info] OK.
```

The file is definitely there, and if I consume the BS _within_ `runStoreS3'` function (the commented line) I get the right result.

**Comment by isovector** [comment] 2019-07-09 04:12
Interesting. I'm pretty sure this is not a bug in polysemy. What happens if you return a strict bytestring from the `Download` handler? What happens if you `deepseq` the result before returning it from `runStoreS3'`?

**Comment by AlexeyRaga** [comment] 2019-07-09 04:35
Then it works. Instead of `deepseq` I am forcing it to print the length within the interpreter (see the commented line). Then I have the full bytestring and I get `[Info] Got: Just 61469`.

I am pretty sure it is not a bug in Polysemy, it is just me not understanding how it supposed to work... I expected (and wanted) it to wrap the rest of the monadic computation with `runResourceT` somehow, but it looks like it only wraps the action itself...

What is interesting though is that when I use `Polysemy.Resource.bracket` then I have this premature closing effect as well:

```haskell
runStoreS3' :: (HasEnv env, Member (Lift (ResourceT IO)) r, Member Resource r, Member (Lift IO) r, Member Log r)
  => env
  -> Sem (Store ': r) a
  -> Sem r a
runStoreS3' env =  interpret $ \case
  Download uri ->
    bracket (logWarn "OPEN") (\_ -> logWarn "CLOSE!") (\_ ->
      sendM @(ResourceT IO) $ runAws @(ResourceT IO) env (downloadFromS3Uri uri)
    )
```

The result then is:
```
[Info] Let's start
[Warn] OPEN
[Warn] CLOSE!
[Info] Got: Just 0
[Info] OK.
```

So as you can see, `CLOSE` happens before the `logInfo` gets its hand on the line.

**Comment by isovector** [comment] 2019-07-09 04:43
The order in which you run your interpreters matters. My guess is that you're running `runBracket` before you're running your `runLogConsole` effect, which would be why you see that. Please post the full code.

**Comment by AlexeyRaga** [comment] 2019-07-09 05:01
The order is like that:

```
runMain :: IO ()
runMain = do
  env <- mkEnv Oregon (\_ _ -> pure ())
  runM
    . runResource
    . runLiftedResourceT
    . runLogConsole
    . runStoreS3' env
    $ stuff
```

I tried having `runLogConsole` before `runResource`, but it didn't make any difference.

The full code is in this repo: https://github.com/AlexeyRaga/attack-score-state/blob/master/src/App/AppMain.hs

**Comment by isovector** [comment] 2019-07-09 13:16
I'll try my best to play around with this today and figure out what's going
on.  Thanks for your patience on this!

**Comment by AlexeyRaga** [comment] 2019-07-17 04:11
I was able to make it work!
It is still kind of a hack, but here is my current way of lifting `ResourceT` into `Resource`:

```haskell
module Effects.ResourceT
( withResourceT
)
where

import Control.Monad                         (mapM)
import Control.Monad.IO.Class                (MonadIO, liftIO)
import Control.Monad.Trans.Resource          (MonadResource, ResourceT, getInternalState, runResourceT, unprotect, createInternalState, runInternalState)
import Control.Monad.Trans.Resource.Internal (ReleaseKey (..), ReleaseMap (..))
import Data.Acquire                          (ReleaseType (..))
import Data.IORef                            (IORef, readIORef)
import Data.Maybe                            (catMaybes)

import Polysemy
import Polysemy.Resource

import Debug.Trace

import qualified Data.IntMap as IntMap

withResourceT :: (Member (Lift IO) r, Member Resource r, Show a) => ResourceT IO a -> (a -> Sem r b) -> Sem r b
withResourceT ma f =
  bracket
    (sendM $ unprotectAll ma)
    (sendM . snd)
    (f . fst)

--------------------------------------------------------------------------------------
unprotectAll :: (Show a) => ResourceT IO a -> IO (a, IO ())
unprotectAll f = do
  ist <- createInternalState
  flip runInternalState ist $ do
    res <- f
    actions <- getAllKeys >>= traverse unprotect
    let cleanup = sequence_ (catMaybes actions)
    pure (res, cleanup)

getAllKeys :: ResourceT IO [ReleaseKey]
getAllKeys = do
  iom <- getInternalState
  m   <- getMap iom
  pure $ ReleaseKey iom <$> IntMap.keys m

getMap :: MonadIO m => IORef ReleaseMap -> m (IntMap.IntMap (ReleaseType -> IO ()))
getMap iom = liftIO $
  readIORef iom >>= \case
    ReleaseMap _ _ m -> pure m
    ReleaseMapClosed -> pure IntMap.empty

```

**Comment by isovector** [comment] 2019-07-17 14:34
If you can put together a small package I can pull and try, I'd be willing to spend some time trying to debug what's going on here. Ideally one that won't require me to have AWS credentials.;

**Comment by AlexeyRaga** [comment] 2019-07-17 23:47
@isovector thanks for looking at it.
I have prepared a minimal example in a branch called `local`: https://github.com/AlexeyRaga/attack-score-state/tree/local

This branch tries to read a local file using `ResourceT` to simulate a typical `ResourceT`-based API as:

```haskell
readFileResource :: FilePath -> ResourceT IO (Maybe LBS.ByteString)
```

**Comment by AlexeyRaga** [comment] 2019-07-18 23:47
I was able to simplify the example even further and without using `ResourceT`. 
I believe that underlying issue is the same, but now it boils to using `bracket` within an interpreter vs. outside the interpreter.

I.e. this interpreter doesn't work as it closes the handle prematurely:

```haskell
data StoreBroken m a where
  GetContent  :: FilePath -> StoreBroken m ByteString

makeSem ''StoreBroken

runBrokenStore :: (Member (Lift IO) r, Member Resource r)
  => Sem (StoreBroken ': r) a
  -> Sem r a
runBrokenStore = interpret $ \case
  GetContent path ->
    bracket
      (sendM $ IO.openFile path IO.ReadMode)
      (\h -> sendM $ IO.hClose h >> print "Closed")
      (\h -> sendM $ print "Using" >> LBS.hGetContents h)
```

I have updated `local` branch with both working and broken examples, and not it is much smaller and easier to comprehend:
https://github.com/AlexeyRaga/attack-score-state/blob/local/src/Effects/Store.hs

**Comment by isovector** [comment] 2019-07-19 00:24
For reference, this is the output I get when running your example:

```
*Main> main
[Info] Running working store
[Info] Got: "long and uninteresting content goes here"
[Info] OK.
[Info] Running broken store
"Using"
"Closed"
```

where using happens before closed.

**Comment by isovector** [comment] 2019-07-19 00:28
Oh, I see --- I'm _also_ getting a `*** Exception: /tmp/test-file.txt: hGetBufSome: illegal operation (handle is closed)`, which is preventing the other info logs. OK, I can repro. I'll dig in.

**Comment by isovector** [comment] 2019-07-19 00:43
[`LBS.hGetContents` uses `unsafeInterleaveIO`](http://hackage.haskell.org/package/bytestring-0.10.10.0/docs/src/Data.ByteString.Lazy.html#hGetContentsN), which doesn't get run until it's actually forced.

You see the same behavior directly in `IO`:

```haskell
runBrokenStore :: FilePath -> IO ByteString
runBrokenStore path =
    bracket
      (IO.openFile path IO.ReadMode)
      (\h -> IO.hClose h >> print "Closed")
      (\h -> print "Using" >> LBS.hGetContents h)


main :: IO ()
main = do
  BS.writeFile filePath "long and uninteresting content goes here"
  print =<< runBrokenStore filePath
```

```
"Using"
"Closed"
"*** Exception: /tmp/test-file.txt: hGetBufSome: illegal operation (handle is closed)
```

**Closed** 2019-07-19 00:44 UTC
Labels: invalid

**Comment by expipiplus1** [comment] 2020-04-12 04:45
Perhaps a little late, but it should be quite easy to use `ResourceT` with a combination of Polysemy's `Resource` and `Input` as `ResourceT` is just a reader over some internal state which is exposed here: https://hackage.haskell.org/package/resourcet-1.2.3/docs/Control-Monad-Trans-Resource.html#g:10
